export const currentUser = { id: "michael", name: "Michael", initial: "M" };

export const places = [
  {
    id: "shop-ramen",
    name: "Shop Ramen",
    cuisine: "Ramen",
    suburb: "Fitzroy",
    price: "$$",
    hours: "Open til 10pm",
    address: "221 Brunswick St, Fitzroy",
    note: "Best tonkotsu in the north. Get the black garlic one. Gets busy after 7 so book or go early.",
    status: "been",
    friendsBeen: 3,
    friendsWant: ["Priya", "Tom", "Jess"],
    image: "/assets/places/shop-ramen.jpg",
  },
  {
    id: "hectors-deli",
    name: "Hector’s Deli",
    cuisine: "Sandwiches",
    suburb: "Brunswick",
    price: "$",
    hours: "Open til 3pm",
    address: "400 Sydney Rd, Brunswick",
    note: "The mortadella sandwich is the move. Go early — they sell out.",
    status: "want",
    friendsBeen: 0,
    friendsWant: [],
    image: "/assets/places/hectors-deli.jpg",
  },
  {
    id: "lagoon-dining",
    name: "Lagoon Dining",
    cuisine: "Chinese",
    suburb: "Carlton",
    price: "$$$",
    hours: "Open til 11pm",
    address: "101 Elgin St, Carlton",
    note: "Order the dry-fried green beans and whatever fish is on.",
    status: "been",
    friendsBeen: 0,
    friendsWant: [],
    image: "/assets/places/lagoon-dining.jpg",
  },
  {
    id: "bar-liberty",
    name: "Bar Liberty",
    cuisine: "Wine bar",
    suburb: "Fitzroy",
    price: "$$$",
    hours: "Open til 11pm",
    address: "234 Johnston St, Fitzroy",
    note: "Natural wine list is deep. Share plates, stay for a second bottle.",
    status: "want",
    friendsBeen: 3,
    friendsWant: ["Priya", "Tom", "Jess"],
    image: "/assets/places/bar-liberty.jpg",
  },
  {
    id: "sunda",
    name: "Sunda",
    cuisine: "Modern Asian",
    suburb: "CBD",
    price: "$$$$",
    hours: "Open til 10pm",
    address: "18 Punch Ln, Melbourne",
    note: "Book ahead. The coconut-braised beef is worth it.",
    status: "been",
    friendsBeen: 0,
    friendsWant: [],
    image: "/assets/places/sunda.jpg",
  },
  {
    id: "ricky-pinky",
    name: "Ricky & Pinky",
    cuisine: "Chinese",
    suburb: "Fitzroy",
    price: "$$",
    hours: "Open til 10pm",
    address: "99 Smith St, Fitzroy",
    note: "Loud, fun, excellent for a group. Get the dry chilli chicken.",
    status: "want",
    friendsBeen: 0,
    friendsWant: [],
    image: "/assets/places/ricky-pinky.jpg",
  },
];

export const friends = [
  { id: "priya", name: "Priya Sharma", phone: "0432 555 010", initial: "P" },
  { id: "tom", name: "Tom Nguyen", phone: "0428 555 001", initial: "T" },
  { id: "jess", name: "Jess Carter", phone: "0401 555 032", initial: "J" },
  { id: "ahmed", name: "Ahmed Rahman", phone: "0420 555 043", initial: "A" },
  { id: "mia", name: "Mia Lopez", phone: "0416 555 054", initial: "M" },
];

export const timeSlots = [
  { id: "fri-7", label: "Fri 18 Sep · 7pm", when: "Fri 18 Sep · 7:00pm" },
  { id: "sat-1", label: "Sat 19 Sep · 1pm", when: "Sat 19 Sep · 1:00pm" },
  { id: "sat-7", label: "Sat 19 Sep · 7pm", when: "Sat 19 Sep · 7:00pm" },
];
